//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FermBook
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class calve
    {
        public int Id { get; set; }
        public int Id_cow_mam { get; set; }
        public Nullable<int> Id_cow_children { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string comment { get; set; }
    
        public virtual cows cow_children { get; set; }
        public virtual cows cow_mam { get; set; }
    }
}
