//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FermBook
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class disease
    {
        public int Id { get; set; }
        public int Id_cow { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string comment { get; set; }
    
        public virtual cows cows { get; set; }
    }
}
