//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FermBook
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseSQLEntities : DbContext
    {
        public DatabaseSQLEntities()
            : base("name=DatabaseSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<calve> calve { get; set; }
        public virtual DbSet<cows> cows { get; set; }
        public virtual DbSet<disease> disease { get; set; }
        public virtual DbSet<insemination> insemination { get; set; }
    }
}
